# Larger default stack for Slint debug builds on Windows MSVC.

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "link-arg=/STACK:8000000"]

[target.aarch64-pc-windows-msvc]
rustflags = ["-C", "link-arg=/STACK:8000000"]

[alias]
android = "build -p uba-android --features build-checks --target"
