import { Button } from "std-widgets.slint";

export component AppWindow inherits Window {
    title: "uba";

    GridLayout {
        spacing: 8px;
        padding: 16px;

        Button {
            text: "TODO";
            row: 0;
            col: 0;
        }

        Button {
            text: "TODO";
            row: 0;
            col: 1;
        }

        Button {
            text: "TODO";
            row: 1;
            col: 0;
        }

        Button {
            text: "TODO";
            row: 1;
            col: 1;
        }

        Button {
            text: "TODO";
            row: 2;
            col: 0;
        }

        Button {
            text: "TODO";
            row: 2;
            col: 1;
        }
    }
}
